backend:
  name: github
  repo: https://github.com/ryanleo5121/Zorpix-Main-test
  branch: main
  base_url: https://api.netlify.com

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}